### ISSUE TITLE
Deleting repo Schematics

### ISSUE THREAD

**Issue by jelle641** [bionicarm/schematics#2]
All of our schematics are in the 3pmap repository, which makes this repository not needed anymore, your thoughts @yochem @moorlag?

**Comment by yochem** [comment]
![archive](https://user-images.githubusercontent.com/23235841/35778872-bee490aa-09c4-11e8-8668-ca9a9315d0b7.png)

Maybe we can archive this repo and state that it are all old files, which will not be used again.

**Comment by jelle641** [comment]
But save the files, just in case. I think that a very good option
